In [1]:
import pandas as pd

** import global supersales dataset using pandas

In [2]:
df = pd.read_excel("C:\\Users\\sippy\\Downloads\\sales data.xlsx")

In [3]:
df.head()

,Row ID,Order ID,Month,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Month .1
0,1,CA-2017-152156,11,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,11
1,2,CA-2017-152156,11,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,11
2,3,CA-2017-138688,6,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,6
3,4,US-2016-108966,10,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,10
4,5,US-2016-108966,10,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,10

In [4]:
df.describe

<bound method NDFrame.describe of       Row ID        Order ID  Month  Order Date  Ship Date       Ship Mode  \
0          1  CA-2017-152156      11 2017-11-08 2017-11-11    Second Class
1          2  CA-2017-152156      11 2017-11-08 2017-11-11    Second Class
2          3  CA-2017-138688       6 2017-06-12 2017-06-16    Second Class
3          4  US-2016-108966      10 2016-10-11 2016-10-18  Standard Class
4          5  US-2016-108966      10 2016-10-11 2016-10-18  Standard Class
...      ...             ...     ...        ...        ...             ...
9795    9796  CA-2017-125920       5 2017-05-21 2017-05-28  Standard Class
9796    9797  CA-2016-128608       1 2016-01-12 2016-01-17  Standard Class
9797    9798  CA-2016-128608       1 2016-01-12 2016-01-17  Standard Class
9798    9799  CA-2016-128608       1 2016-01-12 2016-01-17  Standard Class
9799    9800  CA-2016-128608       1 2016-01-12 2016-01-17  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...
9796          Art           BIC Brite Liner Highlighters, Chisel Tip
9797       Phones                                        GE 30524EE4
9798       Phones           Anker 24W Portable Micro USB Car Charger
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive

         Sales  Month .1
0     261.9600        11
1     731.9400        11
2      14.6200         6
3     957.5775        10
4      22.3680        10
...        ...       ...
9795    3.7980         5
9796   10.3680         1
9797  235.1880         1
9798   26.3760         1
9799   10.3840         1

[9800 rows x 20 columns]>

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Month          9800 non-null   int64
 3   Order Date     9800 non-null   datetime64[ns]
 4   Ship Date      9800 non-null   datetime64[ns]
 5   Ship Mode      9800 non-null   object
 6   Customer ID    9800 non-null   object
 7   Customer Name  9800 non-null   object
 8   Segment        9800 non-null   object
 9   Country        9800 non-null   object
 10  City           9800 non-null   object
 11  State          9800 non-null   object
 12  Postal Code    9789 non-null   float64
 13  Region         9800 non-null   object
 14  Product ID     9800 non-null   object
 15  Category       9800 non-null   object
 16  Sub-Category   9800 non-null   object
 17  Product Name   9800 non-null   object
 18  Sales          9800 non-null   float64
 19  Month .1       9800 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(3), object(13)
memory usage: 1.5+ MB

In [7]:
df.isnull().sum()

Row ID            0
Order ID          0
Month             0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Month .1          0
dtype: int64

In [10]:
duplicates = df.duplicated().sum()

df = df.drop_duplicates()

 ## verify duplicates removed

In [12]:
df.duplicated().sum()

np.int64(0)

#### Convert order date and ship date format

In [13]:
df['Order Date'] = pd.to_datetime(df['Order Date']) 
df['Ship Date '] = pd.to_datetime(df['Ship Date'])

### Verify datatypes

In [14]:
print(df.dtypes)

Row ID                    int64
Order ID                 object
Month                     int64
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Month .1                  int64
Ship Date        datetime64[ns]
dtype: object

In [15]:
df.to_csv("Cleaned_Global_Sales.csv",index = False ) 

print ("Data Cleaning compeleted successfully!!") 
print(" Cleaned file saves as 'Cleaned_Global_Sales.csv' ")

Data Cleaning compeleted successfully!!
 Cleaned file saves as 'Cleaned_Global_Sales.csv'

In [16]:
df.head()

,Row ID,Order ID,Month,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Month .1,Ship Date
0,1,CA-2017-152156,11,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,11,2017-11-11
1,2,CA-2017-152156,11,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,11,2017-11-11
2,3,CA-2017-138688,6,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,6,2017-06-16
3,4,US-2016-108966,10,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,10,2016-10-18
4,5,US-2016-108966,10,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,10,2016-10-18

In [18]:
df.head(10)

,Row ID,Order ID,Month,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Month .1,Ship Date
0,1,CA-2017-152156,11,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,11,2017-11-11
1,2,CA-2017-152156,11,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,11,2017-11-11
2,3,CA-2017-138688,6,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,6,2017-06-16
3,4,US-2016-108966,10,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,10,2016-10-18
4,5,US-2016-108966,10,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,10,2016-10-18
5,6,CA-2015-115812,6,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,6,2015-06-14
6,7,CA-2015-115812,6,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,6,2015-06-14
7,8,CA-2015-115812,6,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,California,90032.0,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,2015-06-14
8,9,CA-2015-115812,6,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,California,90032.0,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,6,2015-06-14
9,10,CA-2015-115812,6,2015-06-09,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,...,California,90032.0,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,6,2015-06-14

In [19]:
df.tail()

,Row ID,Order ID,Month,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Month .1,Ship Date
9795,9796,CA-2017-125920,5,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,...,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798,5,2017-05-28
9796,9797,CA-2016-128608,1,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,...,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368,1,2016-01-17
9797,9798,CA-2016-128608,1,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,...,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188,1,2016-01-17
9798,9799,CA-2016-128608,1,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,...,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376,1,2016-01-17
9799,9800,CA-2016-128608,1,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,...,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384,1,2016-01-17

In [20]:
print(df.shape)

(9800, 21)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Month          9800 non-null   int64
 3   Order Date     9800 non-null   datetime64[ns]
 4   Ship Date      9800 non-null   datetime64[ns]
 5   Ship Mode      9800 non-null   object
 6   Customer ID    9800 non-null   object
 7   Customer Name  9800 non-null   object
 8   Segment        9800 non-null   object
 9   Country        9800 non-null   object
 10  City           9800 non-null   object
 11  State          9800 non-null   object
 12  Postal Code    9789 non-null   float64
 13  Region         9800 non-null   object
 14  Product ID     9800 non-null   object
 15  Category       9800 non-null   object
 16  Sub-Category   9800 non-null   object
 17  Product Name   9800 non-null   object
 18  Sales          9800 non-null   float64
 19  Month .1       9800 non-null   int64
 20  Ship Date      9800 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(3), object(13)
memory usage: 1.6+ MB